 -- TODO: Alter Session set current_schema = 'gvt';
 

PROMPT Creating API Package Specification for Table 'TB_AREA'
--------------------------------------------------------------------------------
-- Name:        cg$TB_AREA
-- Description: TB_AREA table API package declarations
--------------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE gvt.cg$TB_AREA IS


END cg$TB_AREA;
/
