ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER AMDB IDENTIFIED BY amdbpass QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO AMDB;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE TO AMDB;

CREATE USER GVT IDENTIFIED BY wso2pass QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO GVT;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE TO GVT;

CREATE USER SHAREDDB IDENTIFIED BY shareddbpass QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO SHAREDDB;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE TO SHAREDDB;

CREATE USER MI_DB IDENTIFIED BY mipass QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO MI_DB;

CREATE TABLE gvt.tb_genero (
    cd_genero NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ds_genero VARCHAR2(30) NOT NULL
);

CREATE TABLE gvt.tb_rgc (
    cd_rgc NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nu_rgc VARCHAR2(20) NOT NULL UNIQUE,
    dt_emissao DATE NOT NULL,
    nu_bi VARCHAR2(20) UNIQUE,
    dt_emissao_bi DATE,
    cd_rgc_ref VARCHAR2(240),
    nu_repfiscal VARCHAR2(240),
    tp_pessoa VARCHAR2(240),
    no_contribuinte VARCHAR2(240),
    st_contribuinte VARCHAR2(240),
    fl_ativo VARCHAR2(240),
    nu_contribuinte VARCHAR2(240),
    fl_origem VARCHAR2(240),
    sg_contribuinte VARCHAR2(240),
    user_name VARCHAR2(240),
    dni_codctb VARCHAR2(240),
    fl_rgc_validado VARCHAR2(240),
    tp_pessoa_estrangeira VARCHAR2(240),
    fl_dados_cc VARCHAR2(240),
    tp_tipo_contribuinte VARCHAR2(240),
    fl_estado_suspensao VARCHAR2(240),
    fl_processado_soa VARCHAR2(240),
    tp_regime VARCHAR2(240),
    dt_inicio_atv_iva DATE,
    dt_fim_atv_iva DATE,
    fl_saep VARCHAR2(240),
    fl_residente_ausente VARCHAR2(240),
    tp_irt_grupo VARCHAR2(240),
    nu_nif_estrangeiro VARCHAR2(240),
    tp_subtipo_contribuinte VARCHAR2(240),
    fl_estado_contribuinte VARCHAR2(240),
    tp_documento_rgc VARCHAR2(240),
    fl_residente VARCHAR2(240)
);

CREATE TABLE gvt.tb_pessoa (
    cd_pessoa NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    no_completo VARCHAR2(100) NOT NULL,
    dt_nascimento DATE,
    cd_genero NUMBER,
    cd_rgc NUMBER,
    nu_telefone VARCHAR2(20),
    ds_email VARCHAR2(100),
    ds_endereco VARCHAR2(200),
    CONSTRAINT fk_pessoa_genero FOREIGN KEY (cd_genero) REFERENCES gvt.tb_genero(cd_genero),
    CONSTRAINT fk_pessoa_rgc FOREIGN KEY (cd_rgc) REFERENCES gvt.tb_rgc(cd_rgc)
);

CREATE TABLE gvt.tb_departamento (
    cd_departamento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    no_departamento VARCHAR2(100) NOT NULL,
    ds_departamento VARCHAR2(200)
);

CREATE TABLE gvt.tb_area (
    cd_area NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    no_area VARCHAR2(100) NOT NULL,
    ds_area VARCHAR2(200),
    cd_departamento NUMBER,
    CONSTRAINT fk_area_departamento FOREIGN KEY (cd_departamento) REFERENCES gvt.tb_departamento(cd_departamento)
);

CREATE TABLE gvt.tb_funcionario (
    cd_funcionario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nu_matricula VARCHAR2(20) UNIQUE NOT NULL,
    no_cargo VARCHAR2(100),
    dt_admissao DATE,
    cd_departamento NUMBER,
    cd_pessoa NUMBER,
    CONSTRAINT fk_funcionario_departamento FOREIGN KEY (cd_departamento) REFERENCES gvt.tb_departamento(cd_departamento),
    CONSTRAINT fk_funcionario_pessoa FOREIGN KEY (cd_pessoa) REFERENCES gvt.tb_pessoa(cd_pessoa)
);

CREATE TABLE gvt.tb_usuario (
    cd_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    no_username VARCHAR2(50) NOT NULL UNIQUE,
    ds_senha_hash VARCHAR2(200) NOT NULL,
    tp_perfil_acesso VARCHAR2(50) CHECK (tp_perfil_acesso IN ('Administrador', 'Recepcionista', 'Seguranca')),
    fl_estado_conta VARCHAR2(10) DEFAULT 'Ativo' CHECK (fl_estado_conta IN ('Ativo', 'Inativo')),
    cd_pessoa NUMBER,
    CONSTRAINT fk_usuario_pessoa FOREIGN KEY (cd_pessoa) REFERENCES gvt.tb_pessoa(cd_pessoa)
);

CREATE TABLE gvt.tb_visitante (
    cd_visitante NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cd_pessoa NUMBER,
    no_empresa_origem VARCHAR2(100),
    tp_documento_identificacao VARCHAR2(30),
    ds_observacao VARCHAR2(200),
    CONSTRAINT fk_visitante_pessoa FOREIGN KEY (cd_pessoa) REFERENCES gvt.tb_pessoa(cd_pessoa)
);

CREATE TABLE gvt.tb_tipo_visita (
    cd_tipo_visita NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ds_tipo_visita VARCHAR2(100) NOT NULL
);

CREATE TABLE gvt.tb_visita (
    cd_visita NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dt_visita DATE DEFAULT SYSDATE NOT NULL,
    dt_hora_entrada TIMESTAMP,
    dt_hora_saida TIMESTAMP,
    cd_visitante NUMBER NOT NULL,
    cd_funcionario_responsavel NUMBER,
    cd_area NUMBER,
    cd_tipo_visita NUMBER,
    ds_observacao VARCHAR2(300),
    CONSTRAINT fk_visita_visitante FOREIGN KEY (cd_visitante) REFERENCES gvt.tb_visitante(cd_visitante),
    CONSTRAINT fk_visita_funcionario FOREIGN KEY (cd_funcionario_responsavel) REFERENCES gvt.tb_funcionario(cd_funcionario),
    CONSTRAINT fk_visita_area FOREIGN KEY (cd_area) REFERENCES gvt.tb_area(cd_area),
    CONSTRAINT fk_visita_tipo FOREIGN KEY (cd_tipo_visita) REFERENCES gvt.tb_tipo_visita(cd_tipo_visita)
);
 
