name: Sync develop to main

on:
  push:
    branches:
      - develop  # Executa sempre que houver push na develop

permissions:
  contents: write  # Necessário para fazer push na main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0  # Necessário para fazer merge corretamente

      - name: Configura Git
        run: |
          git config user.name "borgitoh"
          git config user.email "kevenconde1998@gmail.com"

      - name: Faz merge de develop -> main
        run: |
          git fetch origin main
          git checkout main
          git merge origin/develop --no-edit || true
          git push origin main
